### PR TITLE
gains author Bolivar

### PR DESCRIPTION
**Pull request by jibarozzo**

### CODE REVIEW

**Review by DrEntropy — APPROVED** [review]
LGTM. I need to get on this myself. as soon as I contribute something that is ;)

**Comment by jibarozzo** [comment]
Not sure why checks fail.

**Comment by jdhoffa** [comment]
> Not sure why checks fail.

FYI, checks failed because the `DESCRIPTION` file was misformatted 😊 
Will fix in a separate PR, but in general we should avoid approving/ merging anything to `main` if checks fails

**Comment by jdhoffa** [comment]
> Not sure why checks fail.

FYI, checks failed because the DESCRIPTION file was improperly formatted (handled in #27).
In general, we should not get in the habit of approving/ merging PRs to `main` when checks fail 😊 

Another note, the `DESCRIPTION` file is super finicky. I always use `usethis` functions (e.g. `usethis::use_author`) to add info to it, as it automatically handles formatting.

**Comment by jibarozzo** [comment]
Agreed. I didn't use that function. 😐

**Comment by DrEntropy** [comment]
Sorry about the premature approval.

**Comment by jibarozzo** [comment]
It's  my bad for not thinking more and juast merging. :/

**Pull request merged**
