### PR TITLE
rename package: update all filenames and file contents to `blazr`

### LINKED ISSUE #4: 💥 rename this repo
A `multiverse` package is [already on CRAN](https://github.com/MUCollective/multiverse) (and seems active), so we may want to start thinking about a new package name

### PR DESCRIPTION
**Pull request by jdhoffa**
We have aligned on the name `blazr` (for now). 
In this PR, I update all file names, and file contents, from `multiverse` -> `blazr`. 

Now, no filenames contain the string `multiverse`:
Screenshot 2024-12-09 at 23 35 01

and no file contents contain the string `multiverse`:
Screenshot 2024-12-09 at 23 37 17

Closes #4

### CODE REVIEW

**Review by jibarozzo — APPROVED** [review]
Cool name!

**Review by asbates — APPROVED** [review]

**Comment by asbates** [comment]
Is the logo going to be a blazer jacket?

**Comment by jibarozzo** [comment]
Blazer jacket with a blazar? 🤯

**Comment by jdhoffa** [comment]
> Is the logo going to be a blazer jacket?

I think a blazing jacket... on fire 🔥

**Pull request merged**
